name: twitchemoticons
description: A library for fetch emotes form FFZ, BTTV and Twitch.
version: 0.1.0
homepage: https://github.com/ManuelGuillen89/twitchemoticons

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
